//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neposedy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcements
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int TeacherId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime PublishDate { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
