//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neposedy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int Id { get; set; }
        public string ParentFullName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ChildFullName { get; set; }
        public Nullable<System.DateTime> ChildBirthDate { get; set; }
        public string DesiredGroup { get; set; }
        public string Comment { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string Status { get; set; }
    }
}
