//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neposedy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        public Children()
        {
            this.Attendance = new HashSet<Attendance>();
            this.ChildParents = new HashSet<ChildParents>();
            this.Notes1 = new HashSet<Notes>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public string MedicalInfo { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ICollection<ChildParents> ChildParents { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual ICollection<Notes> Notes1 { get; set; }
    }
}
