//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neposedy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.Announcements = new HashSet<Announcements>();
            this.Children = new HashSet<Children>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string AgeRange { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Announcements> Announcements { get; set; }
        public virtual ICollection<Children> Children { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
