//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neposedy.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeposedyDBEntities : DbContext
    {
        public NeposedyDBEntities()
            : base("name=NeposedyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Announcements> Announcements { get; set; }
        public DbSet<Applications> Applications { get; set; }
        public DbSet<Attendance> Attendance { get; set; }
        public DbSet<ChildParents> ChildParents { get; set; }
        public DbSet<Children> Children { get; set; }
        public DbSet<Groups> Groups { get; set; }
        public DbSet<Notes> Notes { get; set; }
        public DbSet<Parents> Parents { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Teachers> Teachers { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
