//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neposedy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parents
    {
        public Parents()
        {
            this.ChildParents = new HashSet<ChildParents>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<ChildParents> ChildParents { get; set; }
        public virtual Users Users { get; set; }
    }
}
