//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neposedy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public Teachers()
        {
            this.Announcements = new HashSet<Announcements>();
            this.Groups = new HashSet<Groups>();
            this.Notes = new HashSet<Notes>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Phone { get; set; }
        public string Education { get; set; }
        public Nullable<int> ExperienceYears { get; set; }
    
        public virtual ICollection<Announcements> Announcements { get; set; }
        public virtual ICollection<Groups> Groups { get; set; }
        public virtual ICollection<Notes> Notes { get; set; }
        public virtual Users Users { get; set; }
    }
}
